### ISSUE TITLE
docker image - secure defaults already set?

### ISSUE THREAD

**Issue by muellermichel** [willdurand/docker-hipache#2]
Hey, thanks for your great work on improving hipache security. It looks to me like the https://github.com/hipache/hipache master branch already has secure defaults, however there hasn't been a new stable version released yet, so I'm not comfortable to just use their master branch since I want to go into production as soon as possible. For now I'd like to use your [docker image](https://registry.hub.docker.com/u/willdurand/hipache/). Am I guessing correctly that I have to set up the hipache config.json to use the default https values as outlined in the hipache/hipache master branche's readme? Your docker image is based on this fork, correct?

**Comment by willdurand** [comment]
Hi!

Default security settings are part of the Docker image, it is based on this branch: https://github.com/willdurand/docker-hipache/tree/willdurand-hipache. So it should be secure by default, and this is the Docker image I use in production.

**Comment by muellermichel** [comment]
Great, thank you!
